// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhqbooxncqggzxrbutnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZocWJvb3huY3FnZ3p4cmJ1dG52Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwNDY2MTIsImV4cCI6MjA2ODYyMjYxMn0.aGOeTk2IXb1pJbVflsutnBfDhJmDDULeXJiUMIAXa-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});